version: 2

build:
  os: ubuntu-22.04
  apt_packages:
      - quantum-espresso

python:
    install:
        - method: pip
          path: .
          extra_requirements:
            - docs

sphinx:
    configuration: docs/source/conf.py
    fail_on_warning: false
