name: aiida-qe-hp-docs
channels:
  - conda-forge
dependencies:
  - python=3.9
  - pip
  - aiida-core~=2.3
  - aiida-quantumespresso~=4.3
  - qe=7.2
  - xmltodict
  - jupyterlab=3
  - jupyterlab-myst
  - cryptography>=37.0.4  # lower gives wrong link to openssl
  # documentation
  - myst-parser>=0.18.1
  - myst-nb>=0.17.1
  - sphinx-design
  - sphinx-book-theme
  - sphinx-subfigure>=0.2.4
