default_inputs:
    clean_workdir: True
    property: "raman"
    kpoints_parallel_distance: 0.1
default_protocol: moderate
protocols:
    moderate:
        description: 'Protocol to perform an IR/Raman spectra calculation at normal precision at moderate computational cost.'
    precise:
        description: 'Protocol to perform an IR/Raman spectra calculation at high precision at higher computational cost.'
        kpoints_parallel_distance: 0.075
    fast:
        description: 'Protocol to perform an IR/Raman spectra calculation at low precision at minimal computational cost for testing purposes.'
        kpoints_parallel_distance: 0.3
