default_inputs:
    clean_workdir: True
    options:
        run_parallel: True
        sleep_submission_time: 3.0
default_protocol: moderate
protocols:
    moderate:
        description: 'Protocol to perform an IR/Raman spectra calculation at normal precision at moderate computational cost.'
    precise:
        description: 'Protocol to perform an IR/Raman spectra calculation at high precision at higher computational cost.'
    fast:
        description: 'Protocol to perform an IR/Raman spectra calculation at low precision at minimal computational cost for testing purposes.'
